FullStoryLogin="https://app.fullstory.com/login/"
FullStoryHomePage="https://app.fullstory.com/ui/17P27T/segments/everyone/people/0"
txt_email="xpath=//div[@id='login-container']/div/div/div[2]/div/div[2]/form/div/div/div/input"
txt_password="css=.password > input"
btn_Login="xpath=//span[contains(.,'Log in to FullStory')]"
btn_playSession="css=.fs_component_box:nth-child(1) > .HiVDQEKr5si05XL_g2vGp .\_1QsLtHmDyAmlDAJgbH3wPQ path"
btn_NoteAndShare="id=share"
txtArea_NoteText="css=textarea"
btn_Note="css=.share:nth-child(2)"
Link_Notes="xpath=//a[contains(text(),'Notes')]"
SentToJIRA="xpath=//span[contains(.,'Jira')]"
txt_Summary="css=input:nth-child(1)"
btn_Send="xpath=//div[2]/button/span"
link_highlight="xpath=//a[contains(text(),'highlight.')]"