FullStoryLogin="https://app.fullstory.com/login/"
FullStoryHomePage="https://app.fullstory.com/ui/17P27T/segments/everyone/people/0"
txt_email="xpath=//div[@id='login-container']/div/div/div[2]/div/div[2]/form/div/div/div/input"
txt_password="css=.password > input"
btn_Login="xpath=//span[contains(.,'Log in to FullStory')]"

#Creating Notes for Session and sending Notes to JIRA

btn_playSession="css=.watched > .\_12nOgIHbvYG4xSFAdhxiEb path"
btn_NoteAndShare="id=share"
txtArea_NoteText="css=textarea"
btn_Note="css=.share:nth-child(2)"
Link_Notes="xpath=//a[contains(text(),'Notes')]"
SentToJIRA="xpath=//span[contains(.,'Jira')]"
txt_Summary="css=input:nth-child(1)"
btn_Send="xpath=//div[2]/button/span"
link_highlight="xpath=//a[contains(text(),'highlight.')]"
link_Delete="xpath=//div[7]/div/a/span"

#Integrating JIRA to FS
icon_Profile="css=.selectedState"
btn_Settings="xpath=//div[@id='settingsBtn']/div"
link_ManageIntegration="xpath=//div[5]/div[2]/div/div/a/div/span"
btn_AddJira="//div[@id='AppView']/div[3]/div/div/div/div/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/button/span"
btn_Authorize="xpath=//span[contains(.,'Authorize')]"
Sel_project="id=Project-integration-config-field"
Search_project="xpath=//div[3]/div/div/div/div/input"
Sel_FullStoryAssignment="xpath=//span[contains(.,'Full Story Assignment')]"
Sel_IssueType="xpath=//button[@id='Issue Type-integration-config-field']/span"
Search_IssueType="xpath=//div[3]/div/div/div/div/input"
Sel_Bug="xpath=//li/div/div/div/div/span"
btn_done="//div[3]/div/div[2]/div/button/span"
btn_remove="//span[contains(.,'Remove')]"
btn_manage="css=.fs_component_box:nth-child(7) .GQKPf-wGonH1KQGwFqWke"

#Jira Locators
JiraLoginPage="https://id.atlassian.com/"
txt_JiraEmail="xpath=//input[@id='username']"
btn_JiraLoginContinue="xpath=//button[@id='login-submit']/span/span"
txt_JiraPassword="xpath=//input[@id='password']"
btn_JiraLogIn="xpath=//button[@id='login-submit']/span/span"
JiraHomePage="https://testuserfs.atlassian.net/"
icon_Jira="xpath=//img[contains(@src,'https://fd-assets.prod.atl-paas.net/images/logos/jira-software/jira-software-white.svg')]"
btn_JiraAccept="xpath=//button[contains(text(),'Accept')]"
btn_JiraLogout="xpath=//button[@id='logout-submit']/span/span"
link_JiraLogout="xpath=//div[2]/button/span/span/span"
icon_JiraProfile="xpath=//div[@id='root']/div[3]/div/div[2]/header/div/div[5]/button/span/span/div/span/span"

#Live Coding
SearchBox="css=.header2021-search-box > input"
icon_search="css=.header2021-search-button > .ico"
link_laptop="Linktext=in Laptops / Notebooks"
btn_AddToCart="xpath=//div[@id='ProductBuy']/div/div[2]/button"
Prod_DellLaptop="xpath=(//a[contains(@href, 'https://www.newegg.com/p/1TS-000A-0K6H1?Item=9SIB295G0A6836&cm_sp=SH-_-935109-_-8-_-6-_-9SIB295G0A6836-_-dell-_-dell-_-1')])[2]"